[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Document"
authors = [{name = "Jason Lin", email = "jason40418@gmail.com"}]
dynamic = ["version", "description"]
