##
#  @file
#  Configuration file to build the document.
#
#  @copyright
#  Copyright (c) 2025, Jason Lin. All rights reserved.<BR>
#
#  SPDX-License-Identifier: BSD-3-Clause
#
#  @par Specification Reference:
#
##

name: Build the Document

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  document-build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11']

    runs-on : ${{ matrix.os }}

    steps:
      - name: Checkout the repository and commit
        uses: actions/checkout@v3
        with:
            submodules: 'recursive'
            fetch-depth: 0
            lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Build the Document
        run: |
          python -m sphinx -T -b html -d _build/doctrees -D language=en source html
